name: Snapcraft Action
author: Samuel Meuli
description: GitHub Action for setting up Snapcraft

inputs:
  snapcraft_token:
    description: Token for logging into Snapcraft
    required: true
  skip_install:
    description: Skip installation (login only)
    required: false

runs:
  using: node12
  main: ./index.js

branding:
  icon: upload-cloud
  color: green
