name: Test

on:
  - push
  - pull_request

jobs:
  # Install without login
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Snapcraft should not be installed
        shell: bash
        run: "! snapcraft --version"
      - name: Run action
        uses: ./
      - name: Snapcraft should be installed on macOS/Ubuntu
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: snapcraft --version
      - name: Snapcraft should not be installed on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: "! snapcraft --version"

  # Install with login
  login:
    if: github.event == 'push' && github.repository == 'samuelmeuli/action-snapcraft'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: User should not be logged in
        run: "! snapcraft whoami"
      - name: Run action
        uses: ./
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      - name: User should be logged in
        run: snapcraft whoami

  # Install with lxd
  lxd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Run action
        uses: ./
      - name: lxd should not be available
        run: "! /snap/bin/lxd waitready"
      - name: Run action requesting lxd
        uses: ./
        with:
          use_lxd: true
      - name: lxd should be installed
        run: "/snap/bin/lxd waitready"
